### PR TITLE
Add iOS shortcuts

### PR DESCRIPTION
**Pull request by th0mcat**
I created a couple iOS shortcuts that allow you to send unencrypted reminder requests directly to a room that contains a reminder bot instance.  One is for normal requests, one is for cron requests.  A small time saver for those with large room lists.

### CODE REVIEW

**Review by HarHarLinks — CHANGES_REQUESTED** [review]
Hello, thank you for your contribution. I could test the shortcut for the regular reminder successfully, and I do think the idea is generally neat and absolutely matches my spirit of [hacking matrix tools together](https://matrix.to/#/#pimpyourchat-mcs23:matrix.org)!

Unfortunately the intended cron shortcut does not appear to be correct? Executing it matches what I expected from reading the code; my room received `!c<time>; <message>`.

Note that the syntax for setting cron reminders is `!remindme|remind|r cron <min> <hour> <day of month> <month> <day of week>; <reminder text>`, i.e. `!r cron <time>; <message>`. So the command needs to change slightly from the `!c` command (which is short for `!cancelreminder`) and add a space before the <time> definition.

While I still like the idea, I wonder if we need to consider security carefully here, since we are saving an access token in plain text. On the other hand, the Matrix client like to be already running on the device already has a token, too, and exposes it to the user on demand (though I can't find how it is possible using both Element legacy and X). Probably we should at least add a small warning about handling tokens responsibly?

**Comment by th0mcat** [comment]
🤦 That’s what I get for not testing the cron shortcut while lacking sleep.

I think a warning is a great idea, would you prefer the shortcut itself to have a warning, a warning in the README, or both?

**Comment by HarHarLinks** [comment]
I thought of the README as I wrote this, but maybe you can also find a good way to remind users us this fact as they "install" the shortcut?

**Comment by th0mcat** [comment]
Alright, updated the README as well as the shortcuts to include warnings.

**Pull request merged**
