### PR TITLE
bump nio to support Python 3.12

### PR DESCRIPTION
**Pull request by HarHarLinks**
https://github.com/poljar/matrix-nio/blob/main/CHANGELOG.md

includes some bug fixes, including some around handling e2ee keys. maybe it helps with #98.

### CODE REVIEW

**Comment by HarHarLinks** [comment]
We should bump straight to a python3.12 supporting version as https://github.com/poljar/matrix-nio/pull/461 gets released

**Comment by svierne** [comment]
@HarHarLinks Shouldn't a Python 3.12 classifier be added to `setup()` then? :thinking:

**Comment by HarHarLinks** [comment]
yeah that too, and stuff in a couple more places

**Comment by HarHarLinks** [comment]
I'm removing 3.12 from the CI in #125 so need to add that back too

**Pull request merged**
